import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { ZipCodeBanner } from "@/components/ui/zip-code-banner";
import { AuthProvider } from "@/hooks/use-auth";
import { ZipCodeProvider } from "@/hooks/useZipCode";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ZipCodeProvider>
            <Header />
            {children}
            <Toaster />
            <Footer />
            <ZipCodeBanner />
          </ZipCodeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
